#!/bin/bash
#Like spectacle-welcome, Zenity is merely a placeholder here
zenity --error --title="Dialog is open" --text="You cannot perform this operation while the Welcome Screen is running." --no-wrap
